#!/bin/bash

# Small script to organize output binary files, generated by ww3_multi

WTIME="$1"
STRM="$2"
ENSM="$3"
source /work/noaa/marine/ricardo.campos/work/ww3runs/scripts/input_varsfuncts.sh
DIRW="${DIRWORK}/stream${STRM}/${ENSM}"
DIRR="${DIRRS}/stream${STRM}/${ENSM}"
DIRO="${DIROUT}/stream${STRM}/${ENSM}"
RTIME="$(date -u --date="${WTIME} +${FRESTT} day" '+%Y%m%d')"
LMDEFS=($MDEFS)

cd "${DIRW}"
# clean directory and prepare for the next cycle
rm -f ${DIRW}/ice.*
rm -f ${DIRW}/wind.*
rm -f ${DIRW}/ww3_multi.inp
rm -f ${DIRW}/log.*
rm -f ${DIRW}/rmp_src_to_dst_conserv_*
# move grid/point outputs and restart files
for grid in ${LMDEFS[@]:1:3}; do

  test -f ${DIRW}/${RTIME}.030000.restart.${grid}
  TE=$?
  if [ "$TE" -eq "0" ]; then
    test -f ${DIRR}/${RTIME}.030000.restart.${grid}
    TE=$?
    if [ "$TE" -eq "0" ]; then
      rm -f ${DIRR}/${RTIME}.030000.restart.${grid}
      wait $!
    fi
    mv ${DIRW}/${RTIME}.030000.restart.${grid} ${DIRR}
  fi

  test -f ${DIRW}/out_grd.${grid}
  TE=$?
  if [ "$TE" -eq "0" ]; then
    test -f ${DIRO}/out_grd.${WTIME}.${grid}
    TE=$?
    if [ "$TE" -eq "0" ]; then
      rm -f ${DIRO}/out_grd.${WTIME}.${grid}
      wait $!
    fi
    mv ${DIRW}/out_grd.${grid} ${DIRO}/out_grd.${WTIME}.${grid}
  fi

done
mv ${DIRW}/out_pnt.${LMDEFS[4]} ${DIRO}/out_pnt.${WTIME}.${LMDEFS[4]}
wait $!
rm -f ${DIRW}/*.restart.*
wait $!

